USE [CBF]
GO

/****** Object:  Table [dbo].[Posicao]    Script Date: 28/10/2020 14:44:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Posicao](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](100) NULL,
 CONSTRAINT [PK_Posicao] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


